using UnityEngine;
using System.Collections.Generic;
using Managers;
using Character;
using Character.instance;
using GamePlay.Units;

namespace Grid
{
    /// <summary>
    /// Tactical map manager (pure C# singleton). Manages threat/strategic maps
    /// with incremental frame-based rebuilds driven by TurnManager events.
    /// </summary>
    public class TacticalMapManager
    {
        public static TacticalMapManager Instance { get; } = new TacticalMapManager();

        // Threat map: generated by player units (negative scores)
        public InfluenceMapLayer ThreatMap { get; } = new InfluenceMapLayer();

        // Strategic map: generated by the director/goals (positive scores)
        public InfluenceMapLayer StrategicMap { get; } = new InfluenceMapLayer();


        private List<MapUnit> _pendingRebuildUnits;
        private int _pendingRebuildIndex;

        /// <summary>
        /// Whether the incremental rebuild is complete
        /// </summary>
        public bool IsRebuildComplete =>
            _pendingRebuildUnits == null || _pendingRebuildIndex >= _pendingRebuildUnits.Count;

        /// <summary>Units processed so far (diagnostic)</summary>
        public int BackgroundProcessedCount => _pendingRebuildIndex;

        /// <summary>Total units pending in the current rebuild (diagnostic)</summary>
        public int TotalRebuildCount => _pendingRebuildUnits?.Count ?? 0;

        /// <summary>Whether a rebuild has ever started (distinguishes "done" from "never started")</summary>
        public bool HasRebuildEverStarted { get; private set; }

        /// <summary>
        /// Clears the threat map and snapshots alive players. Triggered by TurnManager
        /// </summary>
        public void BeginIncrementalRebuild()
        {
            ThreatMap.Clear();
            _pendingRebuildUnits = new List<MapUnit>(UnitManager.Instance.GetAllAlivePlayers());
            _pendingRebuildIndex = 0;
            HasRebuildEverStarted = true;
        }

        /// <summary>
        /// Processes one player's threat per tick. True when the last unit finished
        /// </summary>
        public bool TickIncrementalRebuild()
        {
            if (IsRebuildComplete) return true;

            var player = _pendingRebuildUnits[_pendingRebuildIndex];
            if (player != null && player.Character != null)
            {
                RebuildThreatForUnit(player);
            }

            _pendingRebuildIndex++;
            return IsRebuildComplete;
        }

        /// <summary>
        /// Synchronously finishes all remaining rebuild work. Called by AITaskSystem
        /// </summary>
        public void CompleteIncrementalRebuild()
        {
            while (!IsRebuildComplete)
                TickIncrementalRebuild();
        }


        /// <summary>
        /// Synchronous full threat map rebuild (debug use; AI uses incremental instead)
        /// </summary>
        public void RebuildThreatMapSnapshot()
        {
            BeginIncrementalRebuild();
            CompleteIncrementalRebuild();
        }


        private void RebuildThreatForUnit(MapUnit player)
        {
            UnitClassSO playerClass = player.GetClass();
            CharacterInstance playerInstance = player.Character;
            var playerStatus = playerInstance.statSystem;

            float CalculateAttributeThreat(float value, Vector2 range, float coeff)
            {
                float normalized = Mathf.Clamp01((value - range.x) / (range.y - range.x));
                return normalized * coeff;
            }

            float atk = playerStatus.ATK.getValue();
            float atkThreat = CalculateAttributeThreat(atk, playerClass.atkRange, playerClass.atkThreat);

            float def = playerStatus.DEF.getValue();
            float defThreat = CalculateAttributeThreat(def, playerClass.defRange, playerClass.defThreat);

            float hp = playerStatus.maxHP.getValue();
            float hpThreat = CalculateAttributeThreat(hp, playerClass.hpRange, playerClass.hpThreat);

            // moveThreat only scales per-tile intensity; spatial coverage is captured separately by attack range
            float moveRange = (int)player.Character.statSystem.moveRange.getValue() + playerClass.BonusMovementPoints;
            float moveThreat = CalculateAttributeThreat(moveRange, playerClass.moveRangeRange, playerClass.moveRangeThreat);

            float res = playerStatus.RES.getValue();
            float resThreat = CalculateAttributeThreat(res, playerClass.resRange, playerClass.resThreat);

            float speed = playerStatus.Speed.getValue();
            float speedThreat = CalculateAttributeThreat(speed, playerClass.speedRange, playerClass.speedThreat);

            float attackRange = player.NormalAttackSkill?.CastMaxRange ?? 1;
            float attackDistThreat = CalculateAttributeThreat(attackRange, playerClass.attackDistanceRange, playerClass.attackDistanceThreat);

            float maxSkillRange = attackRange;
            var allSkills = player.GetAvailableSkills();
            foreach (var skill in allSkills)
            {
                if (skill.CastMaxRange > maxSkillRange)
                    maxSkillRange = skill.CastMaxRange;
            }
            float skillRangeThreat = CalculateAttributeThreat(maxSkillRange, playerClass.skillRangeDistanceRange, playerClass.skillRangeDistanceThreat);

            float totalThreat =
                atkThreat + defThreat + hpThreat +
                moveThreat + resThreat + speedThreat +
                attackDistThreat + skillRangeThreat;

            float baseThreat = totalThreat * 10f * playerClass.Aggressiveness;

            // Precise move+attack threat range (pathfinding and attack shapes)
            var affectedTiles = player.GetAllPossibleAttackRange();

            // Max Manhattan distance used for threat falloff
            int maxDist = (int)moveRange + (int)maxSkillRange;
            if (maxDist <= 0) maxDist = 1;

            foreach (var tile in affectedTiles)
            {
                int dist = Mathf.Abs(player.gridPosition.x - tile.x) + Mathf.Abs(player.gridPosition.z - tile.z);
                float falloffScore = baseThreat * (1f - (float)dist / (maxDist + 1));
                ThreatMap.AddScore(tile, Mathf.Max(0f, falloffScore));
            }
        }


        public float getThreatRange(int min, int max, int var)
        {
            if (var <= min) return 0f;
            if (var >= max) return 1f;
            return (var - min) / (max - min);
        }

        public float getThreatRange(Vector2 range, int var)
        {
            return getThreatRange((int)range.x, (int)range.y, var);
        }
    }
}
